version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chat
    ports:
      - "5432:5432"
#  ws_server:
#    build:
#      context: ./
#      dockerfile: ./server/Dockerfile
#    depends_on:
#      - web
#    command: python server.py
volumes:
  postgres_data:
