version: '3.9'

services:
  web:
    build: .
    command: bash 'python main.py;pytest'
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chat
    expose:
      - 5432
volumes:
  postgres_data: